Registration Api
shahriaralamsakib/rokomari-clone pull request #1
Opened 2023-12-26 17:27 UTC by shahriaralamsakib

2023-12-26 17:57 UTC, ofsazib requested changes

2023-12-26 17:57 UTC, ofsazib commented on home/__pycache__/__init__.cpython-310.pyc
@shahriaralamsakib Remove all `.pyc` files. The directory `__pycache__` should be added in `/gitignore`

2023-12-26 17:57 UTC, ofsazib commented on home/admin.py
@shahriaralamsakib  The app we create for users/authentication/permission is commonly named as core

2023-12-26 17:57 UTC, ofsazib commented on home/models.py
> +class UserInfo(models.Model):
@shahriaralamsakib  Keep the model name `User` and it should be inherited from Django's abstructbase user model. Get help from internet what is abstrucrbaseuser model

2023-12-26 17:57 UTC, ofsazib commented on home/urls.py
> +     path('users/', AllUsersView.as_view(), name='all-users'),
@shahriaralamsakib Fix indentation.

2023-12-26 17:57 UTC, ofsazib commented on home/models.py
> +class UserInfo(models.Model):
There should be 2 types of user,
1. Cusromer
2. Admin
3. Super User

You can handle the types using a textchoice field

2023-12-26 17:57 UTC, ofsazib commented on rokomari_c/urls.py
> +    path('api/', include('home.urls')),
@shahriaralamsakib  We should have separate url files for each app. Those urls file will be linked in the main urls file

2023-12-30 16:24 UTC, shahriaralamsakib commented on home/admin.py
done

2023-12-30 16:40 UTC, shahriaralamsakib commented on home/__pycache__/__init__.cpython-310.pyc
done

2023-12-30 18:25 UTC, shahriaralamsakib commented on home/urls.py
> +     path('users/', AllUsersView.as_view(), name='all-users'),
done

2024-01-03 04:43 UTC, merged